# Generated by Django 4.1.4 on 2023-01-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phenomenal", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_pic",
            field=models.ImageField(blank=True, null=True, upload_to="cover/"),
        ),
    ]
