# Generated by Django 4.1.4 on 2023-02-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phenomenal", "0004_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(default=1000)),
            ],
        ),
    ]
